version: '2.1'

services:
  djangoapp:
    image: djangoapp:${BUILD_VERSION:-devel}
    command: /bin/sh -c 'echo "READY" && tail -f /dev/null'
    # environment:
    #   - DATABASE_NAME=test_dev
    #   - DATABASE_USER=root
    #   - DATABASE_PASSWORD=test
    #   - DATABASE_HOST=database
    #   - DATABASE_PORT=3306
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/app